#!/usr/bin/env bash
#
# get appmanifest by id
# ex: './appmanifest 244210 | xargs cat | vdf2json |jq' # print appmanifest in json format
#

STEAM_COMPAT_CLIENT_INSTALL_PATH=${STEAM_COMPAT_CLIENT_INSTALL_PATH:-$HOME/.local/share/Steam}

#
function appmanifest ()
{
    read -d "\n" -ra libraryfolders<<<"$(./libraryfolders)"
    for libraryfolder in "${libraryfolders[@]}"; do                
        entries=$(ls $libraryfolder/steamapps/appmanifest_*.acf)
        read -d " "  -ra _entries <<<$entries
        for appmanifest in "${_entries[@]}"; do
            #  manifest=$(cat $appmanifest | vdf2json | jq )
            #  args="--arg libraryfolder $libraryfolder --arg appmanifest $appmanifest"
            #  echo $manifest | jq $args '.AppState | {name,appid,installdir,libraryfolder:$libraryfolder, appmanifest:$appmanifest}'            
            if [  -z  "$1" ]; then
                echo $appmanifest 
            elif [ ! -z  "$1" ] && [ "$libraryfolder/steamapps/appmanifest_$1.acf" == "$appmanifest" ]; then
                echo $appmanifest
                exit
            fi
        done
    done
}
#
appmanifest $1
