#!/usr/bin/env bash

# usage: './appmanifest $STEAM_LIBRARIES'

# Meta
_name=$(basename $0)
_dir="$(
    cd -- "$(dirname "$0")" >/dev/null 2>&1
    pwd -P
)"
_path="$basedir/$fname"

#
libraryfolders=${1:-$HOME/.local/share/Steam/config/libraryfolders.vdf}

#
folders=$(./libraryfolders $libraryfolders)
read -d "\n" -ra _folders <<<$folders
for p in "${_folders[@]}"; do
  entries=$(ls $p/steamapps/appmanifest_*.acf)  
  read -d " "  -ra _entries <<<$entries
  for e in "${_entries[@]}"; do
    echo "$e"

    # if [ "$2" == "json" ]; then
    #   cat $e | vdf2json
    # elif [ "$2" == 'acf' ]; then
    #   cat $e
    # else 
    #   echo "$e"
    # fi
  done
done