#!/usr/bin/env bash
# explore: finding proton

STEAM_COMPAT_CLIENT_INSTALL_PATH=${STEAM_COMPAT_CLIENT_INSTALL_PATH:-$HOME/.local/share/Steam}

function compatToolMapping(){
    echo $(cat ~/.local/share/Steam/config/config.vdf |vdf2json|jq '.InstallConfigStore.Software.Valve.Steam.CompatToolMapping')
}
function find_keys(){
echo $(compatToolMapping |jq 'to_entries|.[]|.key')
}
case "$1" in
map)
    compatToolMapping
;;
names)
    ## TODO: unique
    echo $(compatToolMapping |jq 'to_entries|.[]|select(.value.name!="")|.value.name')
;;
keys)
    read -ra keys <<<"$(find_keys)"
    for key in "${keys[@]}"; do
        echo $key
    done
;;
esac

