#!/usr/bin/env bash
#
# Sets env vars and paths
# to help run an arbitrary command
# on steam wine/proton app prefixes
#

# meta
version=0.0.8
name=$(basename $0)
_dir="$(
    cd -- "$(dirname "$0")" >/dev/null 2>&1
    pwd -P
)"
_name="$_dir/$name"

$_dir/appmanifest | jq -s | jq --arg N $1 '.[]|select(.name|test($N;"i"))|.appid'